# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create(name: "user-")
User.create(name: "user-2")
User.create(name: "user-3")
User.create(name: "user-4")
User.create(name: "user-5")
User.create(name: "user-6")
User.create(name: "user-7")
User.create(name: "user-8")
User.create(name: "user-9")
User.create(name: "user-10")
User.create(name: "user-11")
WorkRecord.create(category_id: 1, user_id: 1)
WorkRecord.create(category_id: 1, user_id: 2)
WorkRecord.create(category_id: 1, user_id: 3)
WorkRecord.create(category_id: 2, user_id: 4)
WorkRecord.create(category_id: 3, user_id: 6)
WorkRecord.create(category_id: 1, user_id: 6)
WorkRecord.create(category_id: 3, user_id: 7)
WorkRecord.create(category_id: 1, user_id: 1)
WorkRecord.create(category_id: 1, user_id: 2)
WorkRecord.create(category_id: 1, user_id: 3)
WorkRecord.create(category_id: 2, user_id: 4)
WorkRecord.create(category_id: 3, user_id: 6)
WorkRecord.create(category_id: 1, user_id: 6)
WorkRecord.create(category_id: 3, user_id: 7)
Category.create(name: "出勤")
Category.create(name: "退勤")
Category.create(name: "退出")
Category.create(name: "再入")
